# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonBlackBeltApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='pythonBlackBeltApp.User'),
        ),
        migrations.AlterField(
            model_name='trip_join',
            name='trip',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='pythonBlackBeltApp.Trip'),
        ),
    ]
