# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonBlackBeltApp', '0002_auto_20160918_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_join',
            name='attendee',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='pythonBlackBeltApp.User'),
        ),
    ]
